// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjzMPMsaXhkVghlZm0xNI4WZgj1af7wF0',
    appId: '1:136031919377:web:8f9b1de0654462b71540b0',
    messagingSenderId: '136031919377',
    projectId: 'movies-app-getx',
    authDomain: 'movies-app-getx.firebaseapp.com',
    storageBucket: 'movies-app-getx.firebasestorage.app',
    measurementId: 'G-R2G8ZH44Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7IgjmCQFMmIiS6tLFM_D2w246wn9wcCw',
    appId: '1:136031919377:android:9ff6114814a5a7f71540b0',
    messagingSenderId: '136031919377',
    projectId: 'movies-app-getx',
    storageBucket: 'movies-app-getx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu0rOmU2Yk0qr1A_uMkmJ5ExUie-9gwRo',
    appId: '1:136031919377:ios:2379bf1f8016adb51540b0',
    messagingSenderId: '136031919377',
    projectId: 'movies-app-getx',
    storageBucket: 'movies-app-getx.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );
}
